Repository Indipage/ANDROID, pull requests merged in 2023-07, with the labels that each got.

#6 [FEAT/#4] Main / navigation 구현
  app/build.gradle.kts
  app/src/main/java/com/indipage/presentation/MainActivity.kt
  app/src/main/java/com/indipage/presentation/article/ArticleFragment.kt
  app/src/main/java/com/indipage/presentation/profile/MyPageFragment.kt
  app/src/main/java/com/indipage/presentation/search/SearchFragment.kt
  app/src/main/java/com/indipage/presentation/ticket/TicketFragment.kt
  app/src/main/res/drawable/ic_navigation_article_off.xml
  app/src/main/res/drawable/ic_navigation_article_on.xml
  app/src/main/res/drawable/ic_navigation_my_page_off.xml
  app/src/main/res/drawable/ic_navigation_my_page_on.xml
  app/src/main/res/drawable/ic_navigation_search_off.xml
  app/src/main/res/drawable/ic_navigation_search_on.xml
  app/src/main/res/drawable/ic_navigation_ticket_off.xml
  app/src/main/res/drawable/ic_navigation_ticket_on.xml
  app/src/main/res/drawable/selector_article_icon.xml
  app/src/main/res/drawable/selector_my_page_icon.xml
  app/src/main/res/drawable/selector_search_icon.xml
  app/src/main/res/drawable/selector_ticket_icon.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_article.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_ticket.xml
  app/src/main/res/menu/menu_main_nav.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 소현이

#13 Feature/#12 feat saved article
  .github/pull_request_template.md
  app/src/main/java/com/indipage/data/api/BookMarkApiService.kt
  app/src/main/java/com/indipage/data/datasource/BookMarkDataSource.kt
  app/src/main/java/com/indipage/data/datasource/remote/BookMarkDataSourceImpl.kt
  app/src/main/java/com/indipage/data/dto/response/SavedArticle.kt
  app/src/main/java/com/indipage/data/repositoryimpl/BookMarkRepositoryImpl.kt
  app/src/main/java/com/indipage/di/ApiModule.kt
  app/src/main/java/com/indipage/di/DataSourceModule.kt
  app/src/main/java/com/indipage/di/RepoModule.kt
  app/src/main/java/com/indipage/domain/repository/BookMarkRepository.kt
  app/src/main/java/com/indipage/presentation/TestRecyclerviewPagingAdapter.kt
  app/src/main/java/com/indipage/presentation/profile/MyPageFragment.kt
  app/src/main/java/com/indipage/presentation/savedarticle/SavedArticleAdapter.kt
  app/src/main/java/com/indipage/presentation/savedarticle/SavedArticleFragment.kt
  app/src/main/java/com/indipage/presentation/savedarticle/SavedArticleViewModel.kt
  app/src/main/res/drawable/ic_article_move.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/radius_article_button.xml
  app/src/main/res/drawable/radius_article_item.xml
  app/src/main/res/font/font_pretendard_regular.xml
  app/src/main/res/font/font_pretendard_semibold.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_saved_article.xml
  app/src/main/res/layout/item_saved_article.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/appearances.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 삭

#18 Feauture/#17 my page
  app/src/main/java/com/indipage/presentation/profile/MyPageFragment.kt
  app/src/main/java/com/indipage/presentation/savedarticle/SavedArticleFragment.kt
  app/src/main/java/com/indipage/presentation/savedspace/SavedSpaceFragment.kt
  app/src/main/java/com/indipage/util/BindingAdapter.kt
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_saved_space.xml
  app/src/main/res/values/strings.xml
Labels: ✨ [FEAT], 💄 [UI], 👩‍👧‍👧 인디언 삭

#20 [Feature/#14] article detail / view 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/indipage/presentation/article/ArticleDetailActivity.kt
  app/src/main/java/com/indipage/presentation/article/ArticleDetailAdapter.kt
  app/src/main/java/com/indipage/presentation/article/ArticleDetailData.kt
  app/src/main/res/drawable/ic_article_detail_arrow.xml
  app/src/main/res/drawable/ic_article_detail_bookmark_off.xml
  app/src/main/res/drawable/ic_article_detail_bookmark_on.xml
  app/src/main/res/layout/activity_article_detail.xml
  app/src/main/res/layout/item_article_detail_article_body.xml
  app/src/main/res/layout/item_article_detail_article_image.xml
  app/src/main/res/layout/item_article_detail_article_title.xml
  app/src/main/res/menu/menu_article_detail_app_bar.xml
  app/src/main/res/values/strings.xml
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 소현이, 💄 [UI]

#22 Feature/#10 space detail
  app/build.gradle.kts
  app/src/main/java/com/indipage/data/dto/response/MockCurationData.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseCurationDto.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseSpaceDetailDto.kt
  app/src/main/java/com/indipage/presentation/MainActivity.kt
  app/src/main/java/com/indipage/presentation/search/SearchFragment.kt
  app/src/main/java/com/indipage/presentation/spacedetail/SpaceDetailCurationAdapter.kt
  app/src/main/java/com/indipage/presentation/spacedetail/SpaceDetailFragment.kt
  app/src/main/java/com/indipage/presentation/spacedetail/SpaceDetailTagAdapter.kt
  app/src/main/res/drawable/round_rectangle.xml
  app/src/main/res/drawable/shape_purple_fill_20_rect.xml
  app/src/main/res/drawable/shape_purple_unfill_rect.xml
  app/src/main/res/layout/fragment_space_detail.xml
  app/src/main/res/layout/item_space_detail_curation.xml
  app/src/main/res/layout/item_space_detail_tag.xml
  app/src/main/res/navigation/navigation_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 소민이, 💄 [UI]

#31 Feature/#24 search fragment UI 작업
  app/src/main/java/com/indipage/data/dto/response/Search.kt
  app/src/main/java/com/indipage/presentation/savedspace/SavedSpaceAdapter.kt
  app/src/main/java/com/indipage/presentation/search/SearchAdapter.kt
  app/src/main/java/com/indipage/presentation/search/SearchFragment.kt
  app/src/main/java/com/indipage/util/Debouncer.kt
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/shape_gray200_fill_8_rect.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/layout/item_search_keyword.xml
Labels: 👩‍👧‍👧 인디언 소민이, 💄 [UI]

#26 [Feature/#23] article detail tag / 태그 수정
  app/src/main/java/com/indipage/presentation/article/ArticleDetailActivity.kt
  app/src/main/java/com/indipage/presentation/article/ArticleDetailAdapter.kt
  app/src/main/java/com/indipage/presentation/article/ArticleDetailAdapterViewHolder.kt
  app/src/main/java/com/indipage/util/Constants.kt
  app/src/main/res/drawable/ic_article_detail_go_to_place_detail_arrow.xml
  app/src/main/res/layout/activity_article_detail.xml
  app/src/main/res/layout/item_article_detail_article_body.xml
  app/src/main/res/layout/item_article_detail_article_title.xml
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 소현이, 💄 [UI]

#28 Feature/#25 refactor UI
  app/src/main/java/com/indipage/presentation/savedarticle/SavedArticleFragment.kt
  app/src/main/java/com/indipage/presentation/savedspace/SavedSpaceFragment.kt
  app/src/main/res/drawable/shape_image_5_rect.xml
  app/src/main/res/layout/fragment_card.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_saved_article.xml
  app/src/main/res/layout/fragment_saved_space.xml
  app/src/main/res/layout/fragment_ticket.xml
  app/src/main/res/layout/item_saved_article.xml
  app/src/main/res/layout/item_saved_space.xml
  app/src/main/res/values/appearances.xml
  app/src/main/res/values/strings.xml
Labels: 💄 [UI], 👩‍👧‍👧 인디언 삭

#35 [Feature/#27] article detail event / 클릭 이벤트 적용
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/indipage/presentation/article/ArticleDetailAdapterViewHolder.kt
  app/src/main/java/com/indipage/presentation/article/ArticleDetailFragment.kt
  app/src/main/java/com/indipage/presentation/article/ArticleFragment.kt
  app/src/main/res/drawable/ic_article_detail_bookmark_off.xml
  app/src/main/res/drawable/selector_article_detail_bookmark.xml
  app/src/main/res/layout/fragment_article.xml
  app/src/main/res/layout/fragment_article_detail.xml
  app/src/main/res/menu/menu_article_detail_app_bar.xml
  app/src/main/res/navigation/navigation_main.xml
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 소현이

#40 [Feature/#39] article detail / api 연결, 북마크 클릭 수정
  app/src/main/java/com/indipage/data/dto/response/ResponseArticleDetailDto.kt
  app/src/main/java/com/indipage/presentation/article/ArticleDetailFragment.kt
  app/src/main/java/com/indipage/presentation/article/ArticleDetailViewModel.kt
  app/src/main/res/drawable/selector_article_detail_bookmark.xml
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 소현이

#44 [UI]: 해쉬태그, 조르기 버튼 UI 작업
  app/src/main/java/com/indipage/data/api/SpaceDetailApiService.kt
  app/src/main/java/com/indipage/data/datasource/SpaceDetailDataSource.kt
  app/src/main/java/com/indipage/data/datasource/remote/SpaceDetailDataSourceImpl.kt
  app/src/main/java/com/indipage/data/dto/BaseResponse.kt
  app/src/main/java/com/indipage/data/dto/response/MockCurationData.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseBooleanData.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseSpaceArticle.kt
  app/src/main/java/com/indipage/data/repositoryimpl/SpaceDetailRepositoryImpl.kt
  app/src/main/java/com/indipage/domain/repository/SpaceDetailRepository.kt
  app/src/main/java/com/indipage/presentation/spacedetail/SpaceDetailFragment.kt
  app/src/main/java/com/indipage/presentation/spacedetail/SpaceDetailTagAdapter.kt
  app/src/main/java/com/indipage/presentation/spacedetail/SpaceDetailViewModel.kt
  app/src/main/java/com/indipage/util/BindingAdapter.kt
  app/src/main/res/drawable/selector_follow_button.xml
  app/src/main/res/drawable/shape_black_fill_20_rect.xml
  app/src/main/res/layout/fragment_space_detail.xml
  app/src/main/res/layout/item_space_detail_tag.xml
Labels: 👩‍👧‍👧 인디언 소민이, 💄 [UI]

#45 [Feature/#43] article / article view ui 구성
  app/src/main/java/com/indipage/presentation/article/ArticleFragment.kt
  app/src/main/res/drawable/ic_article_card_gradient_open.xml
  app/src/main/res/drawable/ic_article_card_gradient_pre.xml
  app/src/main/res/drawable/img_article_card_packed.xml
  app/src/main/res/drawable/selector_article_category_button_back.xml
  app/src/main/res/drawable/selector_article_category_button_text.xml
  app/src/main/res/drawable/shape_gray200_fill_40_rect.xml
  app/src/main/res/drawable/shape_purple_fill_40_rect.xml
  app/src/main/res/layout/fragment_article.xml
  app/src/main/res/layout/item_weekly_article_open.xml
  app/src/main/res/layout/item_weekly_article_pre.xml
  app/src/main/res/values/appearances.xml
  app/src/main/res/values/strings.xml
Labels: 👩‍👧‍👧 인디언 소현이, 💄 [UI]

#47 Feature/#42 api 연동
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/indipage/presentation/qr/DialogQrFailFragment.kt
  app/src/main/java/com/indipage/presentation/qr/QrSuccessFragment.kt
  app/src/main/java/com/indipage/presentation/spacedetail/SpaceDetailFragment.kt
  app/src/main/java/com/indipage/presentation/ticket/CardFragment.kt
  app/src/main/java/com/indipage/presentation/ticket/TicketFragment.kt
  app/src/main/java/com/indipage/presentation/ticket/TicketItemHelper.kt
  app/src/main/java/com/indipage/presentation/ticket/TicketViewModel.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/navigation/navigation_main.xml
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 삭

#49 [Feature/#41] main / navigation icon 변경
  app/src/main/res/drawable/ic_navigation_article_off.xml
  app/src/main/res/drawable/ic_navigation_article_on.xml
  app/src/main/res/drawable/ic_navigation_my_page_off.xml
  app/src/main/res/drawable/ic_navigation_my_page_on.xml
  app/src/main/res/drawable/ic_navigation_search_off.xml
  app/src/main/res/drawable/ic_navigation_search_on.xml
  app/src/main/res/drawable/ic_navigation_ticket_off.xml
  app/src/main/res/drawable/ic_navigation_ticket_on.xml
  app/src/main/res/layout/activity_main.xml
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 소현이

#53 Feature/#51 article detail ticket api
  app/src/main/java/com/indipage/data/api/ArticleDetailApiService.kt
  app/src/main/java/com/indipage/data/api/TestApiService.kt
  app/src/main/java/com/indipage/data/datasource/ArticleDetailDataSource.kt
  app/src/main/java/com/indipage/data/datasource/remote/ArticleDetailDataSourceImpl.kt
  app/src/main/java/com/indipage/data/dto/request/RequestTicketReceiveDto.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseArticleDetailDto.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseTicketReceiveCheckDto.kt
  app/src/main/java/com/indipage/data/repositoryimpl/ArticleDetailRepositoryImpl.kt
  app/src/main/java/com/indipage/di/ApiModule.kt
  app/src/main/java/com/indipage/domain/repository/ArticleDetailRepository.kt
  app/src/main/java/com/indipage/presentation/article/ArticleDetailFragment.kt
  app/src/main/java/com/indipage/presentation/article/ArticleDetailViewModel.kt
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 소현이

#59 [Feature/#58] article / weekly api
  app/src/main/java/com/indipage/data/api/ArticleApiService.kt
  app/src/main/java/com/indipage/data/datasource/ArticleDataSource.kt
  app/src/main/java/com/indipage/data/datasource/remote/ArticleDataSourceImpl.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseArticleWeeklyDto.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseWeeklyArticleDto.kt
  app/src/main/java/com/indipage/data/repositoryimpl/ArticleRepositoryImpl.kt
  app/src/main/java/com/indipage/di/ApiModule.kt
  app/src/main/java/com/indipage/di/DataSourceModule.kt
  app/src/main/java/com/indipage/di/RepoModule.kt
  app/src/main/java/com/indipage/domain/repository/ArticleRepository.kt
  app/src/main/java/com/indipage/presentation/article/ArticleFragment.kt
  app/src/main/java/com/indipage/presentation/article/ArticleViewModel.kt
  app/src/main/java/com/indipage/presentation/article/WeeklyArticleAdapter.kt
  app/src/main/java/com/indipage/presentation/article/WeeklyArticleAdapterViewHolder.kt
  app/src/main/java/com/indipage/util/BindingAdapter.kt
  app/src/main/res/layout/fragment_article.xml
  app/src/main/res/layout/item_weekly_article_open.xml
  app/src/main/res/layout/item_weekly_article_pre.xml
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 소현이

#61 [Feature/#60] article all / ui 구성
  app/src/main/res/layout/fragment_article_all.xml
Labels: 👩‍👧‍👧 인디언 소현이, 💄 [UI]

#63 Feature/#56 space detail refector
  app/src/main/java/com/indipage/data/api/SpaceDetailApiService.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseSpaceDetailDto.kt
  app/src/main/java/com/indipage/presentation/spacedetail/SpaceDetailFragment.kt
  app/src/main/java/com/indipage/presentation/spacedetail/SpaceDetailViewModel.kt
  app/src/main/res/layout/fragment_space_detail.xml
  app/src/main/res/values/strings.xml
Labels:  ♻️ [REFACTOR], 👩‍👧‍👧 인디언 소민이

#65 [Feature/#62] article all / list api
  app/src/main/java/com/indipage/data/api/ArticleDetailApiService.kt
  app/src/main/java/com/indipage/data/datasource/ArticleDetailDataSource.kt
  app/src/main/java/com/indipage/data/datasource/remote/ArticleDetailDataSourceImpl.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseArticleAllDto.kt
  app/src/main/java/com/indipage/data/repositoryimpl/ArticleDetailRepositoryImpl.kt
  app/src/main/java/com/indipage/domain/repository/ArticleDetailRepository.kt
  app/src/main/java/com/indipage/presentation/article/ArticleAllAdapter.kt
  app/src/main/java/com/indipage/presentation/article/ArticleAllFragment.kt
  app/src/main/java/com/indipage/presentation/article/ArticleAllViewModel.kt
  app/src/main/java/com/indipage/presentation/article/ArticleFragment.kt
  app/src/main/res/drawable/shape_black_fill_bottom10_rect.xml
  app/src/main/res/layout/fragment_article_all.xml
  app/src/main/res/layout/item_article_all.xml
  app/src/main/res/navigation/navigation_main.xml
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 소현이

#70 [Feature/#66,#67] article detail bookmark api / slide api
  app/build.gradle.kts
  app/src/main/java/com/indipage/data/api/ArticleApiService.kt
  app/src/main/java/com/indipage/data/api/ArticleDetailApiService.kt
  app/src/main/java/com/indipage/data/datasource/ArticleDataSource.kt
  app/src/main/java/com/indipage/data/datasource/ArticleDetailDataSource.kt
  app/src/main/java/com/indipage/data/datasource/remote/ArticleDataSourceImpl.kt
  app/src/main/java/com/indipage/data/datasource/remote/ArticleDetailDataSourceImpl.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseArticleBookmarkDto.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseArticleSlideDto.kt
  app/src/main/java/com/indipage/data/repositoryimpl/ArticleDetailRepositoryImpl.kt
  app/src/main/java/com/indipage/data/repositoryimpl/ArticleRepositoryImpl.kt
  app/src/main/java/com/indipage/domain/repository/ArticleDetailRepository.kt
  app/src/main/java/com/indipage/domain/repository/ArticleRepository.kt
  app/src/main/java/com/indipage/presentation/article/ArticleAllAdapter.kt
  app/src/main/java/com/indipage/presentation/article/ArticleDetailFragment.kt
  app/src/main/java/com/indipage/presentation/article/ArticleDetailViewModel.kt
  app/src/main/java/com/indipage/presentation/article/ArticleFragment.kt
  app/src/main/java/com/indipage/presentation/article/ArticleViewModel.kt
  app/src/main/java/com/indipage/presentation/article/WeeklyArticleAdapterViewHolder.kt
  app/src/main/res/drawable/ic_article_all_ticket.xml
  app/src/main/res/layout/fragment_article.xml
  app/src/main/res/layout/item_article_all.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/fragment_article_scene.xml
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 소현이

#72 Feature/#69 search rv filter
  app/src/main/java/com/indipage/data/dto/response/ResponseSearchDto.kt
  app/src/main/java/com/indipage/data/dto/response/Search.kt
  app/src/main/java/com/indipage/presentation/search/SearchAdapter.kt
  app/src/main/java/com/indipage/presentation/search/SearchFragment.kt
  app/src/main/java/com/indipage/presentation/search/SearchViewModel.kt
  app/src/main/java/com/indipage/util/Debouncer.kt
  app/src/main/res/drawable/ic_search_place_blank.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/menu/menu_main_nav.xml
  app/src/main/res/values/strings.xml
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 소민이

#74 Feautre/#68 rv item click
  app/src/main/java/com/indipage/presentation/MainActivity.kt
  app/src/main/java/com/indipage/presentation/profile/MyPageFragment.kt
  app/src/main/java/com/indipage/presentation/qr/QrSuccessFragment.kt
  app/src/main/java/com/indipage/presentation/savedarticle/SavedArticleAdapter.kt
  app/src/main/java/com/indipage/presentation/savedarticle/SavedArticleFragment.kt
  app/src/main/java/com/indipage/presentation/savedarticle/SavedArticleViewModel.kt
  app/src/main/java/com/indipage/presentation/savedspace/SavedSpaceAdapter.kt
  app/src/main/java/com/indipage/presentation/savedspace/SavedSpaceFragment.kt
  app/src/main/java/com/indipage/presentation/savedspace/SavedSpaceViewModel.kt
  app/src/main/java/com/indipage/presentation/spacedetail/SpaceDetailFragment.kt
  app/src/main/java/com/indipage/presentation/ticket/CardAdapter.kt
  app/src/main/java/com/indipage/presentation/ticket/CardFragment.kt
  app/src/main/java/com/indipage/presentation/ticket/CardViewModel.kt
  app/src/main/java/com/indipage/presentation/ticket/TicketFragment.kt
  app/src/main/res/layout/fragment_card.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_ticket.xml
  app/src/main/res/layout/item_saved_article.xml
  app/src/main/res/layout/item_saved_space.xml
  app/src/main/res/layout/item_ticket_card.xml
  app/src/main/res/navigation/navigation_main.xml
Labels: ✨ [FEAT], ❌ [DEl],  ♻️ [REFACTOR], ➕ [ADD], ✅ [MOD], 👩‍👧‍👧 인디언 삭

#80 Feature/#75 all UI refactor
  app/src/main/java/com/indipage/data/datasource/remote/SpaceDetailDataSourceImpl.kt
  app/src/main/java/com/indipage/presentation/MainActivity.kt
  app/src/main/java/com/indipage/presentation/ticket/CardFragment.kt
  app/src/main/java/com/indipage/presentation/ticket/TicketFragment.kt
  app/src/main/java/com/indipage/presentation/ticket/TicketItemHelper.kt
  app/src/main/java/com/indipage/presentation/ticket/TicketViewModel.kt
  app/src/main/res/layout/fragment_card.xml
  app/src/main/res/layout/fragment_saved_article.xml
  app/src/main/res/layout/fragment_saved_space.xml
  app/src/main/res/layout/fragment_ticket.xml
  app/src/main/res/navigation/navigation_main.xml
  core-ui/src/main/java/com/example/core_ui/base/BindingFragment.kt
Labels: ✨ [FEAT], 🎀 [CHORE], ✅ [MOD], 👩‍👧‍👧 인디언 삭

#77 [UI] Splash 화면 및 mipmap 수정
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/background_splash_screen.xml
  app/src/main/res/drawable/ppp_club_icon_2x.png
  app/src/main/res/drawable/ppp_club_img.png
  app/src/main/res/drawable/ppp_club_logo.xml
  app/src/main/res/mipmap-hdpi/ppp_club_img_2x.png
  app/src/main/res/mipmap-hdpi/ppp_club_logo_2x.png
Labels: 👩‍👧‍👧 인디언 소민이, 💄 [UI]

#79 [Feature/#71] article refactoring, bug fix
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/indipage/data/api/ArticleApiService.kt
  app/src/main/java/com/indipage/data/api/ArticleDetailApiService.kt
  app/src/main/java/com/indipage/data/datasource/ArticleDataSource.kt
  app/src/main/java/com/indipage/data/datasource/ArticleDetailDataSource.kt
  app/src/main/java/com/indipage/data/datasource/remote/ArticleDataSourceImpl.kt
  app/src/main/java/com/indipage/data/datasource/remote/ArticleDetailDataSourceImpl.kt
  app/src/main/java/com/indipage/data/repositoryimpl/ArticleDetailRepositoryImpl.kt
  app/src/main/java/com/indipage/data/repositoryimpl/ArticleRepositoryImpl.kt
  app/src/main/java/com/indipage/domain/repository/ArticleDetailRepository.kt
  app/src/main/java/com/indipage/domain/repository/ArticleRepository.kt
  app/src/main/java/com/indipage/presentation/article/ArticleAllFragment.kt
  app/src/main/java/com/indipage/presentation/article/ArticleAllViewModel.kt
  app/src/main/java/com/indipage/presentation/article/ArticleFragment.kt
  app/src/main/java/com/indipage/presentation/article/ArticleViewModel.kt
  app/src/main/java/com/indipage/presentation/article/WeeklyArticleAdapter.kt
  app/src/main/java/com/indipage/presentation/article/WeeklyArticleAdapterViewHolder.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailAdapter.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailAdapterViewHolder.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailData.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailFragment.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailViewModel.kt
  app/src/main/java/com/indipage/util/Constants.kt
  app/src/main/res/drawable/ic_article_list_gradient.xml
  app/src/main/res/layout/fragment_article.xml
  app/src/main/res/layout/fragment_article_all.xml
  app/src/main/res/layout/item_article_all.xml
  app/src/main/res/layout/item_weekly_article_open.xml
  app/src/main/res/navigation/navigation_main.xml
Labels:  ♻️ [REFACTOR], 👩‍👧‍👧 인디언 소현이, 🔨 [FIX]

#84 [Feature/#82] all article refactoring
  app/src/main/java/com/indipage/presentation/article/ArticleAllAdapter.kt
  app/src/main/java/com/indipage/presentation/article/ArticleFragment.kt
  app/src/main/java/com/indipage/presentation/article/ArticleViewModel.kt
  app/src/main/java/com/indipage/presentation/article/WeeklyArticleAdapterViewHolder.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailAdapterViewHolder.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailData.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailFragment.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailViewModel.kt
  app/src/main/res/drawable/ic_article_detail_up.xml
  app/src/main/res/layout/fragment_article.xml
  app/src/main/res/layout/fragment_article_detail.xml
  app/src/main/res/layout/item_article_all.xml
  app/src/main/res/layout/item_article_detail_article_body.xml
  app/src/main/res/layout/item_article_detail_article_image.xml
  app/src/main/res/layout/item_article_detail_article_title.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/fragment_article_scene.xml
Labels:  ♻️ [REFACTOR], 👩‍👧‍👧 인디언 소현이, 💄 [UI], 🔨 [FIX]

#88 Feature/#86 feat move s6m1n
  app/src/main/java/com/indipage/presentation/spacedetail/SpaceDetailFragment.kt
  app/src/main/java/com/indipage/presentation/spacedetail/SpaceDetailViewModel.kt
  app/src/main/res/layout/fragment_space_detail.xml
  app/src/main/res/values/appearances.xml
Labels: ✨ [FEAT], 👩‍👧‍👧 인디언 소민이, 👩‍👧‍👧 인디언 삭

#89 [feature/#87] article-refactoring / 화면 이동
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailAdapterViewHolder.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailFragment.kt
Labels: 👩‍👧‍👧 인디언 소현이, 🔨 [FIX]

#97 Feature/#92 space detail button
  app/src/main/res/layout/fragment_space_detail.xml
  app/src/main/res/values/strings.xml
Labels: 👩‍👧‍👧 인디언 소민이, 💄 [UI]

#98 [Feature/#95] article view fix
  app/src/main/java/com/indipage/presentation/article/ArticleFragment.kt
  app/src/main/java/com/indipage/presentation/article/ArticleViewModel.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailAdapterViewHolder.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailFragment.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailViewModel.kt
  app/src/main/java/com/indipage/util/Constants.kt
  app/src/main/res/layout/item_article_detail_bottom_ticket.xml
  app/src/main/res/layout/item_article_detail_head.xml
Labels:  ♻️ [REFACTOR], 👩‍👧‍👧 인디언 소현이, 🔨 [FIX]

#102 [feature / #100] article QA 진행중
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailBottomTicketAdapter.kt
  app/src/main/res/layout/item_article_detail_bottom_ticket.xml
Labels: 👩‍👧‍👧 인디언 소현이, 💄 [UI]

#104 Feature/#103 qa somin
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/indipage/presentation/ticket/TicketFragment.kt
  app/src/main/res/drawable/shape_black_transparent.xml
  app/src/main/res/drawable/space_detail_gradient_black.xml
  app/src/main/res/layout/fragment_dialog_qr_fail.xml
  app/src/main/res/layout/fragment_space_detail.xml
  app/src/main/res/layout/item_saved_article.xml
  app/src/main/res/mipmap-hdpi/ppp_club_logo_2x.png
  app/src/main/res/mipmap-hdpi/ppp_club_logo_center_3x.png
  app/src/main/res/values/dialog_theme.xml
  app/src/main/res/values/strings.xml
Labels: 👩‍👧‍👧 인디언 소민이, 💄 [UI]

#106 Feature/#100 article qa 2
  app/src/main/java/com/indipage/presentation/article/ArticleAllAdapter.kt
  app/src/main/java/com/indipage/presentation/article/ArticleFragment.kt
  app/src/main/java/com/indipage/presentation/article/ArticleViewModel.kt
  app/src/main/java/com/indipage/presentation/articleall/ArticleAllFragment.kt
  app/src/main/java/com/indipage/presentation/articleall/ArticleAllViewModel.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailFragment.kt
  app/src/main/res/layout/fragment_article.xml
  app/src/main/res/layout/fragment_article_all.xml
  app/src/main/res/layout/item_article_all.xml
  app/src/main/res/navigation/navigation_main.xml
Labels: 👩‍👧‍👧 인디언 소현이, 🔨 [FIX]

#111 Feature/#100 article qa 4
  app/src/main/java/com/indipage/data/dto/response/ResponseTicketReceiveCheckDto.kt
  app/src/main/java/com/indipage/presentation/article/ArticleFragment.kt
  app/src/main/java/com/indipage/presentation/articleall/ArticleAllAdapter.kt
  app/src/main/java/com/indipage/presentation/articleall/ArticleAllFragment.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailAdapterViewHolder.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailBottomTicketAdapter.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailFragment.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailSnackBar.kt
  app/src/main/res/drawable/img_article_detail_ticket_empty.png
  app/src/main/res/layout/article_detail_snackbar.xml
  app/src/main/res/layout/item_article_detail_bottom_ticket.xml
Labels: 👩‍👧‍👧 인디언 소현이, 🔨 [FIX]

#115 [UI] : 더미 데이터 기반 ui 수정
  app/src/main/res/layout/item_article_all.xml
  app/src/main/res/layout/item_weekly_article_open.xml
Labels: 👩‍👧‍👧 인디언 소현이, 💄 [UI]

#116 [FIX] article detail ticket 크기 변경
  app/src/main/res/drawable/img_article_detail_ticket_empty.png
  app/src/main/res/layout/item_article_detail_bottom_ticket.xml
Labels: 👩‍👧‍👧 인디언 소현이, 🔨 [FIX]

#118 [UI] : UI 수정
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailSnackBar.kt
  app/src/main/res/layout/item_article_detail_bottom_ticket.xml
Labels: 👩‍👧‍👧 인디언 소현이, 🔨 [FIX]

#125 Feature/#123 domain entity
  app/src/main/java/com/indipage/data/api/BookMarkApiService.kt
  app/src/main/java/com/indipage/data/api/TicketApiService.kt
  app/src/main/java/com/indipage/data/datasource/BookMarkDataSource.kt
  app/src/main/java/com/indipage/data/datasource/TicketDataSource.kt
  app/src/main/java/com/indipage/data/datasource/remote/BookMarkDataSourceImpl.kt
  app/src/main/java/com/indipage/data/datasource/remote/TicketDataSourceImpl.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseArticleDto.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseCardDto.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseSpaceDto.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseTicketDto.kt
  app/src/main/java/com/indipage/data/repositoryimpl/BookMarkRepositoryImpl.kt
  app/src/main/java/com/indipage/data/repositoryimpl/TicketRepositoryImpl.kt
  app/src/main/java/com/indipage/domain/entity/Article.kt
  app/src/main/java/com/indipage/domain/entity/Space.kt
  app/src/main/java/com/indipage/domain/entity/Ticket.kt
  app/src/main/java/com/indipage/domain/repository/BookMarkRepository.kt
  app/src/main/java/com/indipage/domain/repository/TicketRepository.kt
  app/src/main/java/com/indipage/presentation/savedarticle/SavedArticleAdapter.kt
  app/src/main/java/com/indipage/presentation/savedarticle/SavedArticleViewModel.kt
  app/src/main/java/com/indipage/presentation/savedspace/SavedSpaceAdapter.kt
  app/src/main/java/com/indipage/presentation/savedspace/SavedSpaceViewModel.kt
  app/src/main/java/com/indipage/presentation/ticket/CardAdapter.kt
  app/src/main/java/com/indipage/presentation/ticket/CardFragment.kt
  app/src/main/java/com/indipage/presentation/ticket/CardViewModel.kt
  app/src/main/java/com/indipage/presentation/ticket/TicketAdapter.kt
  app/src/main/java/com/indipage/presentation/ticket/TicketFragment.kt
  app/src/main/java/com/indipage/presentation/ticket/TicketViewModel.kt
  app/src/main/res/layout/item_saved_article.xml
  app/src/main/res/layout/item_saved_space.xml
  app/src/main/res/layout/item_ticket_card.xml
  app/src/main/res/layout/item_ticket_ticket.xml
Labels:  ♻️ [REFACTOR], ➕ [ADD], 👩‍👧‍👧 인디언 삭

#134 Feature/#131 space detail refector
  app/src/main/java/com/indipage/data/api/SearchApiService.kt
  app/src/main/java/com/indipage/data/api/SpaceDetailApiService.kt
  app/src/main/java/com/indipage/data/datasource/SearchDataSource.kt
  app/src/main/java/com/indipage/data/datasource/SpaceDetailDataSource.kt
  app/src/main/java/com/indipage/data/datasource/remote/SearchDataSourceImpl.kt
  app/src/main/java/com/indipage/data/datasource/remote/SpaceDetailDataSourceImpl.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseCurationDto.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseSearchDto.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseSpaceArticle.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseSpaceDetailDto.kt
  app/src/main/java/com/indipage/data/repositoryimpl/SearchRepositoryImpl.kt
  app/src/main/java/com/indipage/data/repositoryimpl/SpaceDetailRepositoryImpl.kt
  app/src/main/java/com/indipage/domain/entity/Curation.kt
  app/src/main/java/com/indipage/domain/entity/Search.kt
  app/src/main/java/com/indipage/domain/entity/SpaceArticle.kt
  app/src/main/java/com/indipage/domain/entity/SpaceDetail.kt
  app/src/main/java/com/indipage/domain/repository/SearchRepository.kt
  app/src/main/java/com/indipage/domain/repository/SpaceDetailRepository.kt
  app/src/main/java/com/indipage/presentation/search/SearchAdapter.kt
  app/src/main/java/com/indipage/presentation/search/SearchFragment.kt
  app/src/main/java/com/indipage/presentation/search/SearchViewModel.kt
  app/src/main/java/com/indipage/presentation/spacedetail/SpaceDetailCurationAdapter.kt
  app/src/main/java/com/indipage/presentation/spacedetail/SpaceDetailFragment.kt
  app/src/main/java/com/indipage/presentation/spacedetail/SpaceDetailTagAdapter.kt
  app/src/main/java/com/indipage/presentation/spacedetail/SpaceDetailViewModel.kt
  app/src/main/res/layout/fragment_space_detail.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/layout/item_space_detail_curation.xml
Labels:  ♻️ [REFACTOR], 👩‍👧‍👧 인디언 소민이, ✅ [MOD]

#133 [Feature/#128] entity 추가, view holder 분리
  app/src/main/java/com/indipage/data/api/ArticleApiService.kt
  app/src/main/java/com/indipage/data/api/ArticleDetailApiService.kt
  app/src/main/java/com/indipage/data/datasource/ArticleDataSource.kt
  app/src/main/java/com/indipage/data/datasource/ArticleDetailDataSource.kt
  app/src/main/java/com/indipage/data/datasource/remote/ArticleDataSourceImpl.kt
  app/src/main/java/com/indipage/data/datasource/remote/ArticleDetailDataSourceImpl.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseArticleAllDto.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseArticleBookmarkDto.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseArticleDetailDto.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseArticleSlideDto.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseArticleWeeklyDto.kt
  app/src/main/java/com/indipage/data/dto/response/ResponseTicketReceiveCheckDto.kt
  app/src/main/java/com/indipage/data/repositoryimpl/ArticleDetailRepositoryImpl.kt
  app/src/main/java/com/indipage/data/repositoryimpl/ArticleRepositoryImpl.kt
  app/src/main/java/com/indipage/domain/entity/ArticleAll.kt
  app/src/main/java/com/indipage/domain/entity/ArticleBookmark.kt
  app/src/main/java/com/indipage/domain/entity/ArticleDetail.kt
  app/src/main/java/com/indipage/domain/entity/ArticleSlide.kt
  app/src/main/java/com/indipage/domain/entity/ArticleWeekly.kt
  app/src/main/java/com/indipage/domain/entity/TicketReceiveCheck.kt
  app/src/main/java/com/indipage/domain/repository/ArticleDetailRepository.kt
  app/src/main/java/com/indipage/domain/repository/ArticleRepository.kt
  app/src/main/java/com/indipage/presentation/article/ArticleViewModel.kt
  app/src/main/java/com/indipage/presentation/article/WeeklyArticleAdapter.kt
  app/src/main/java/com/indipage/presentation/article/WeeklyArticleAdapterViewHolder.kt
  app/src/main/java/com/indipage/presentation/articleall/ArticleAllAdapter.kt
  app/src/main/java/com/indipage/presentation/articleall/ArticleAllViewModel.kt
  app/src/main/java/com/indipage/presentation/articleall/viewholder/ArticleAllViewHolder.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailAdapter.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailBottomAdapter.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailBottomTicketAdapter.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailHeadAdapter.kt
  app/src/main/java/com/indipage/presentation/articledetail/ArticleDetailViewModel.kt
  app/src/main/java/com/indipage/presentation/articledetail/viewholder/ArticleDetailAdapterViewHolder.kt
  app/src/main/java/com/indipage/presentation/articledetail/viewholder/ArticleDetailBottomTicketViewHolder.kt
  app/src/main/java/com/indipage/presentation/articledetail/viewholder/ArticleDetailBottomViewHolder.kt
  app/src/main/java/com/indipage/presentation/articledetail/viewholder/ArticleDetailHeadViewHolder.kt
  app/src/main/res/layout/fragment_article.xml
  app/src/main/res/layout/fragment_article_detail.xml
  app/src/main/res/layout/item_article_all.xml
  app/src/main/res/layout/item_article_detail_bottom.xml
  app/src/main/res/layout/item_article_detail_bottom_ticket.xml
  app/src/main/res/layout/item_article_detail_head.xml
  app/src/main/res/layout/item_weekly_article_open.xml
  app/src/main/res/layout/item_weekly_article_pre.xml
Labels:  ♻️ [REFACTOR], 👩‍👧‍👧 인디언 소현이, ✅ [MOD]
